name: cuidapet_api_dart
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dotenv: ^3.0.0
  get_it: ^7.2.0
  logger: ^1.1.0
  mysql1: ^0.19.2
  shelf: ^1.1.0

dev_dependencies:
  pedantic: ^1.10.0
